[project]
name = "claude-capstone"
version = "0.1.0"
description = "capstone project for Agentic AI System desingn Course"
authors = [
    {name = "aekkasathvik",email = "aekkasathvik2002@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "python-dotenv (>=1.2.3,<2.0.0)",
    "openai (>=3.17.0,<4.0.0)",
    "chromadb (>=1.5.9,<2.0.0)",
    "rich (>=15.0.0,<16.0.0)",
    "pydantic (>=2.13.5,<3.0.0)"
]

[tool.poetry]
packages = [{include = "Educosys_Claude"}]


[tool.poetry.scripts]
educosys_claude = "Educosys_Claude.main:run"
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
